---
title: "Final Project Data Memo"
author: "Hailey Broderick and Callum Weinberg"
date: "January 19, 2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Overview of Dataset

For our final project, we plan on using the Global Environmental Indicators dataset provided as a dataset on Kaggle. The dataset can be accessed here: https://www.kaggle.com/ruchi798/global-environmental-indicators ^[Ruchi Bhatia; UNSD Global Environment Statistics. (2021; June). GLobal Environmental Indicators, Version 1. Retrieved January 21, 2022 from https://www.kaggle.com/ruchi798/global-environmental-indicators.]

The dataset was put together by UNSD (United Nations Statistics Division) Global Environmental Statistics. The Kaggle auther is Ruchi Bhatia. The dataset was compiled by surveying nations' "stastistical offices and/or ministries of environment (or equivalent institutions) in response to the biennial UNSD/UNEP Questionnaire on Environment Statistics".

The dataset is a compilation of datasets, which correspond to different environmental indicators at national levels. The main categories are Air and Climate, Biodiversity, Energy and Minerals, Forests, Governance, Inland Water Resources, Land and Angrigulture, Marine and Coastal Areas, Natural Disasters, and Waste. There are roughly 50 comma separated files between all the categories, each with a corresponding Excel file that operates as the data dictionary. Each file has a number of metrics related to environmental indicators, and the nation in question. The files reviewed so far all have one observation per nation. However this varies a bit depending on the file, as some datasets have portions of sub-areas broken out into their own observations, and in some datasets are missing nations. Therefore most of the datasets have 150-250 observations. Some of the datasets have a country ID, but it is missing in some of the csv files. There will need to be some data cleaning done to merge the files.

We plan on exploring most metrics available as predictors (so long as they make sense in a temporal manner). Therefore there will likely be over 50 predictors initially considered. Some of the csv files have more than one metric worth considering. As mentioned above, there are missing observations for some of the metrics. Some smaller countries are often missing data. We will have to take an approach for which we both exclude predictors with a lot of missing information, but will likely include some predictors with small amounts of missing data, and implement a methodology to handle the missing data.
\newline

## Overview of Research Questions

The variable which we are interested in predicting is the renewable electricity production percentage for different countries.

In predicting this variable we are interested in answering a few questions. We are interested in answering which countries are predicted to have highest and lowest renewable electricity production percentages. In achieving accurate predictions, we would like to venture to draw conclusions about where countries should aim their resources in order to raise renewable electricity production as a percentage of their total electricity production. This information would be beneficial because it could provide an indication as to the best way to invest in renewable electricity sources, versus nonrenewable electricity sources, which pose a threat to our climate and precious resources.

Our response variable is renewable electricity production percentage (REPP). In order to describe our response variable, we must first discuss total electricity production, which is defined as gross electricity production. That is, the sum of the electrical energy production by all generating units. Our response variable, renewable electricity production percentage (REPP), is defined as the proportion of total electricity produced that comes from a renewable origin. A renewable origin may be electricity produced from hydro, geothermal, solar, wind, tide, wave, and ocean sources.

These questions may be best answered with a regression approach, since we are predicting a quantitative variable.

From the vast dataset, there are many predictors to consider and initially we plan on including many. Examples of predictors which may be especially useful include: Air and Climate predictors (emissions), Inland Water Resources (Water abstractions), Forest area, and Marine/Coastal Areas. We additionally may consider other metrics from these categories.
\newline

## Proposed Timeline

We will be dividing up the workload for the project and working in the following manner. We will begin by loading and tidying our data set this week. Callum will spearhead the merging of our datasets.

Once we get our data set loaded and cleaned, we next plan on beginning exploratory data analysis. Hailey will create summary graphs for our outcome variable (distribution) as well as explore and summarize particularly important predictor variables using graphs/plots. We also want to include at least one correlation chart. Callum will summarize our missing data and we will collaborate on finding the best way to handle missing observations (Callum will lead this part given his experience), and create possible maps for our predictions. EDA work will be divided appropriately, and we will each perform written analysis on our respective parts.

For feature extraction, we will meet and make a plan about perspective models. Then, we will each create a number of appropriate models, and review each others models to discuss their viability.

Data splitting is next. Hailey will take charge of initially dividing data into test and training sets and use stratisfied sampling. Together, we will use cross-validation to fold training set.

Next, we will begin model fitting, where Callum and Hailey will each fit at least two model classes. We will next tune models across resamples (at this stage we may examine each other’s models to offer thoughts on tuning). After tuning, together we will choose our optimal model, fitting it to training and test sets. We will then evaluate the performance of our model and write up an analysis.

Laslty, we will both contribute to the executive summary, including key findings which we each made throughout the project. Once we have our project in final stage, we will go back and make sure that we included proper narration to our respective parts throughout the paper (including and introduction and conclusion). The last step is revision, in which we will each go over the project and in its entirety and make final edits anywhere we see fit. Finally, we will properly organize our files, code, and data as required and submit our final project.
\newline


## Any Questions or Concerns

Given the approach of this project will include considering a relatively large number of predictors, we anticipate a few issues may arise. We will likely need to consider some shrinkage or subset methods for a regression based approach, given $n$ might not be that much larger than $p$. Additionally, we will likely need to consider some missing-data related strategies other than dropping observations, given the variation in which predictors are missing for which countries (most countries will likely be missing from at least one predictor). We don't have any questions at the moment, but appreciate the instructor support.

